baseurl = "https://pseudo.co.de/"
languageCode = "en-us"
title = "Cloud Deployment Framework"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
  # General information
  author = "Justin Menga"
  description = "Cloud Deployment Framework"
  copyright = "Released under the MIT license"

  # Repository
  # provider = "GitHub"
  # repo_url = "https://github.com/casecommons/aws-docs"

  version = "v0.1"
  logo = "images/logo.png"
  favicon = ""

  permalink = "#"

  # Custom assets
  custom_css = []
  custom_js  = []

  # Syntax highlighting theme
  highlight_css  = ""

  [params.palette]
      primary = "red"
      accent  = "teal"

    [params.font]
      text = "Ubuntu"
      code = "Ubuntu Mono"

[social]
  twitter = "jmenga"
  github  = "mixja"
  email   = "justin.menga@gmail.com"


[[menu.main]]
  name   = "Introduction"
  url    = "/"
  weight = 0

[[menu.main]]
  name   = "Tutorial"
  url    = "tutorial/"
  weight = 10

[[menu.main]]
  name   = "Security Resources"
  url    = "security-resources/"
  weight = 20

[[menu.main]]
  name   = "CloudFormation Resources"
  url    = "cloudformation-resources/"
  weight = 30

[[menu.main]]
  name   = "License"
  url    = "license/"
  weight = 40


[blackfriday]
  smartypants = true
  fractions = true
  smartDashes = true
  plainIDAnchors = true
